baseURL = "http://huanglianjing.com/"
languageCode = "en-us"
title = "huanglianjing"
theme = "papermod"

[Menus]
  main = [
      {Name = "Categories", Weight = 1, URL = "/categories/"},
      {Name = "Tags", Weight = 2, URL = "/tags/"}
  ]
